# Generated by Django 5.2.10 on 2026-01-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_category_name'),
        ('orders', '0007_deduplicate_menu_items'),
    ]

    operations = [
    ]
