# Generated by Django 5.2.10 on 2026-01-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20260125_0554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('category', 'name')},
        ),
    ]
