# Generated by Django 5.2.10 on 2026-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway')], default='DELIVERY', max_length=20),
        ),
    ]
