# Generated by Django 5.2.10 on 2026-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_menuitem_description_order_fulfillment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
