# Generated by Django 5.2.10 on 2026-01-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_menuitem_cost_price_orderitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('UNDELIVERED', 'Undelivered')], default='UNDELIVERED', max_length=20),
        ),
    ]
